### ISSUE TITLE
'NoneType' object has no attribute 'start_server' After update to 4.2.1

### ISSUE THREAD

**Issue by thecircleisround** [r0x0r/pywebview#1159]
### Specification
- pywebview version: 4.2.1
- operating system: Mac OS 12.6
- web renderer: Cocoa

### Description
After updating to pywebview 4.2.1, getting error `'NoneType' object has no attribute 'start_server'` when passing flask server instance. Application worked fine on 3.6.3

### Practicalities

- YES/NO I am willing to work on this issue myself.
No
- YES/NO I am prepared to support this issue financially.
No

Edit: 

Downgrading to 4.1 seems to fix the issue. 4.2 and 4.2.1 do not work

**Comment by r0x0r** [comment]
I just pushed a fix to the master. Please test it.

**Comment by r0x0r** [comment]
The fix is released as 4.2.2
