### ISSUE TITLE
Not starting on python 3.9

### ISSUE THREAD

**Issue by microsoftisevil** [r0x0r/pywebview#780]
### Specification
- pywebview version: 3.5
- operating system: Mint 20.2
- web renderer: qt/gtk

### Description  
  
This minimal example;
```
import webview

window = webview.create_window('Woah dude!', 'https://pywebview.flowrl.com')
webview.start()
```
run fine with python3.8 and under, but not with python3.9. Is pywebview not ready for 3.9? According to pypi it should.

```
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/ws03/.local/lib/python3.9/site-packages/webview/guilib.py", line 16, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/ws03/.local/lib/python3.9/site-packages/webview/platforms/gtk.py", line 25, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "/home/ws03/.local/lib/python3.9/site-packages/webview/guilib.py", line 29, in import_qt
    import webview.platforms.qt as guilib
  File "/home/ws03/.local/lib/python3.9/site-packages/webview/platforms/qt.py", line 29, in <module>
    from PyQt5 import QtCore
ImportError: cannot import name 'QtCore' from 'PyQt5' (/usr/lib/python3/dist-packages/PyQt5/__init__.py)
Traceback (most recent call last):
  File "/media/ws03/storage_backup/files/pro/works/software/programs/Absistence/absistence/src/utils/configurator/test.py", line 4, in <module>
    webview.start()
  File "/home/ws03/.local/lib/python3.9/site-packages/webview/__init__.py", line 122, in start
    guilib = initialize(gui)
  File "/home/ws03/.local/lib/python3.9/site-packages/webview/guilib.py", line 93, in initialize
    raise WebViewException('You must have either QT or GTK with Python extensions installed in order to use pywebview.')
webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.

```
and if i try with `gui='qt'`
```
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "/home/ws03/.local/lib/python3.9/site-packages/webview/guilib.py", line 29, in import_qt
    import webview.platforms.qt as guilib
  File "/home/ws03/.local/lib/python3.9/site-packages/webview/platforms/qt.py", line 29, in <module>
    from PyQt5 import QtCore
ImportError: cannot import name 'QtCore' from 'PyQt5' (/usr/lib/python3/dist-packages/PyQt5/__init__.py)
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/ws03/.local/lib/python3.9/site-packages/webview/guilib.py", line 16, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/ws03/.local/lib/python3.9/site-packages/webview/platforms/gtk.py", line 25, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
Traceback (most recent call last):
  File "/media/ws03/storage_backup/files/pro/works/software/programs/Absistence/absistence/src/utils/configurator/test.py", line 4, in <module>
    webview.start(gui='qt')
  File "/home/ws03/.local/lib/python3.9/site-packages/webview/__init__.py", line 122, in start
    guilib = initialize(gui)
  File "/home/ws03/.local/lib/python3.9/site-packages/webview/guilib.py", line 93, in initialize
    raise WebViewException('You must have either QT or GTK with Python extensions installed in order to use pywebview.')
webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.
```

**Comment by r0x0r** [comment]
This is a problem with dependencies. Googling for this GTK error offers plenty of explanations and solutions. As for QT, it works on my system by reinstalling PyQT dependencies for Python 3.9

**Comment by microsoftisevil** [comment]
Of course i did that and on more than one machine. What's your OS?

**Comment by r0x0r** [comment]
Ubuntu 20.04

**Comment by microsoftisevil** [comment]
So! You're right it's a dependency thing but the error isn't form python itself even though it work with 3.8 because it makes the same thing when i try to make a basic empty window with Gtk directly with python 3.9.
Looks like the problem is in Gtk for Python3.9. :/

**Comment by microsoftisevil** [comment]
P.S. Please consider moving from github, who trust them now that it's microsoft.. I have to verify pywebview sources every time i reinstall!
