### ISSUE TITLE
[Cocoa] Crash when creating custom menu items

### ISSUE THREAD

**Issue by forceflow1049** [r0x0r/pywebview#1707]
When creating a window with custom menu items on 6.0, the app crashes. The same code runs fine on 5.4, and creating a window without a menu works fine on 6.0.

Trace:
```bash
Traceback (most recent call last):
  File "Exhibitera_Apps.py", line 4, in <module>
  File "exhibitera/apps/Apps.py", line 376, in run
    webview.start(func=start_app, menu=menu_items, private_mode=False)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "webview/__init__.py", line 281, in start
  File "webview/platforms/cocoa.py", line 1352, in create_window
  File "webview/platforms/cocoa.py", line 1348, in create
  File "webview/platforms/cocoa.py", line 715, in first_show
  File "webview/platforms/cocoa.py", line 84, in windowDidBecomeKey_
  File "webview/platforms/cocoa.py", line 982, in _recreate_menus
  File "webview/platforms/cocoa.py", line 1135, in _add_custom_menu
  File "webview/platforms/cocoa.py", line 1109, in process_menu_items
AttributeError: 'functools.partial' object has no attribute '__name__'. Did you mean: '__ne__'?
```

Here's the menu I'm creating:

```python

webview_menu.Menu(
                    'Settings',
                    [
                        webview_menu.MenuAction('Show settings', partial(apps_webview.show_webview_window, 'settings',
                                                                         {'reload': True})),
                        webview_menu.Menu('Configure',
                      [
                          webview_menu.MenuAction('DMX Control',
                                                  partial(apps_webview.show_webview_window,
                                                          'dmx_control')),
                                                
... [many more MenuActions] ...

                          webview_menu.MenuAction('Word Cloud Viewer',
                                                  partial(apps_webview.show_webview_window,
                                                          'word_cloud_viewer_setup')),
                      ])
                    ]
                )

```

None of the 6.0 breaking changes seem to be related to this, so I was expecting it to work as previously.

**Comment by r0x0r** [comment]
I pushed a fix to master. Please test if it resolves your issue.
